# Generated by Django 4.1.4 on 2023-02-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerceA', '0002_alter_category_options_alter_product_options'),
        ('cart', '0002_rename_cart_id_cart_cart_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaetItem',
            new_name='cartitem',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cartitem',
        ),
    ]
